### PR TITLE
Manage attachments on contract templates

### PR DESCRIPTION
**Pull request by fcayre**
Attachments are contractual documents so they must be displayed and managed on the form.

### CODE REVIEW

**Comment by legalsylvain** [comment]
C'est "ocabot merge patch"

**Comment by fcayre** [comment]
> C'est "ocabot merge patch"

oups, oui pas encore l'habitude, merci :)

**Comment by fcayre** [comment]
> C'est "ocabot merge patch"

oups, oui pas encore l'habitude, merci :)

**Pull request merged**
